name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWM3M2ZlNWItNTBiZS00MzE0LWIyZDctYjVlOWQ1OTk4ZDcwIiwidGVuYW50X2lkIjoiMTNkYWZmZmQzZmViYjMyNmU0NGUxN2VhOGJmYzA2Zjc5ZDE3YjA4MTcxM2QyZTVhZjhlMDM2ZmIyMmYwMGExMyIsImludGVybmFsX3NlY3JldCI6Ijc5NWEyMjViLTRhNmMtNDRlNy05OWViLWNhYzFkMDU1ZDI4NyJ9.sLUGQBKp8ANDW68jiiyUOi1G9JC-xyfFEvrnMf7KU2U"
JWT_SECRET="monuSecret"

